### ISSUE TITLE
I don't know how to implement transaction with Waterline

### ISSUE THREAD

**Issue by jyoungrok** [balderdashy/waterline#960] opened 2015-04-22 08:36 UTC
Actually, i posted for that issue, but administrator closed that issue with solution but it doesn't work
so i re-post this issue
My post was " https://github.com/balderdashy/waterline/issues/614 "
please, refer upper post

I'd like to implement transaction with multiple query 
but i think waterline doesn't support that.
It it true?

i mean ... should i make new connection to my database server(mysql) instead of waterline for using transaction

Please, don't close this issue without perfect solution ... I will check your reply ASAP

**Comment by dmarcelino** [comment] 2015-04-22 09:37
Hi @jyoungrok, that is true, transactions are not yet supported in waterline, please take a look at #755 which is the request to add transactions. Feel free to discuss the feature there if you have any suggestions/concerns regarding the API.

If you are using sails-mysql or sails-postgresql you can try using the adapter's `.query()` method, which allows you to run a *raw* SQL query against the DB, more details on: https://github.com/balderdashy/waterline-docs/blob/master/query-methods.md#query-query-data-callback-

Alternatively you can do as you suggest and create a different connection to the DB without using waterline.

There are rarely perfect solutions in life but this is question is a duplicate of #755 and I'm afraid I'll have to close it for now. You can still add comments to it and if you feel really strongly about it you can reopen.

**Closed by dmarcelino** 2015-04-22 09:37 UTC
Labels: question
