### ISSUE TITLE
Issue/Bug when updating model with binary field

### ISSUE THREAD

**Issue by tobiasviehweger** [balderdashy/waterline#475] opened 2014-06-13 21:38 UTC
Hi there.. 

I think there is a bug in waterline for the following scenario. Take a model with a binary attribute. Assumption: Entry for this model exists on the DB already, we fetch the value and try to update it using:

```javascript
User.findOne({ id: user.id  }).exec(function (err, dbUser) {
      //Update any value
      dbUser.name = 'lala';

      //User has field profileImage which is of type Buffer
      var isBuffer = Buffer.isBuffer(dbUser.profileImage); // == true

      //Update on DB
      dbUser.save(function(err) {
           //Error: binary expected but Object found
      });
});
```

When trying this, an error is thrown from a waterline validation (as I could see it's actually an anchor validation). The problem is, that the validation checks if the binary-value is a Buffer object (which it was before calling save). However in the following call stack this gets lost:

waterline/model/lib/defaultMethods/save.js/updateRecord => proto.toObject
waterline/model/lib/defaultMethods/toObject.js/addProperties: _.cloneDeep

In the lodash clone method, it only checks for [object Object] and loses the Buffer prototype ref. This is bad ... I'm not quite sure what would be the best way to fix this, as I'm quite new to nodejs & sails.. It seems though that lodash supports a  custom callback for cloneDeep which will be called for conversion, maybe this could be used to have an exception for Buffer objects - though I'm not sure if there are other use cases where this could be problematic as well.

It would be no problem for me to do a fix, but before I start I wanted to clarify what the best option would be..

Ideas? :)
Thanks, Tobi

**Comment by zonetti** [comment] 2015-01-16 12:44
Is there a hotfix I can use for now?

**Comment by zonetti** [comment] 2015-01-20 17:02
Apparently the same problem was happening while saving with the `create` method (https://github.com/balderdashy/waterline/issues/792)

**Comment by particlebanana** [comment] 2015-01-20 18:02
Yeah we can copy the same fix to the `update` method I believe. In most cases I would recommend using streams to pipe binary files somewhere else like S3 just as a general note on storing buffers.

**Comment by zonetti** [comment] 2015-01-27 20:12
I'm using the static `update` for now:

```javascript
// this doesn't work
mymodel.binaryFile = binaryFile;
mymodel.save(callback);

// this works
mymodel.binaryFile = binaryFile;
MyModel.update({id: mymodel.id}, mymodel).exec(callback);
```

**Comment by dmarcelino** [comment] 2015-04-24 17:04
> The amount of cloning going on there is really insane..

Agreed, we probably should investigate which clones are actually needed.

Is this issue still ongoing? Does anyone have a fix they would like to PR?

**Comment by dmarcelino** [comment] 2015-05-07 17:53
Closing this as unresponsive, anyway this seems a duplicate of balderdashy/sails-mongo#253.

**Closed** 2015-05-07 17:53 UTC
Labels: needs answer
