### ISSUE TITLE
watelineJS: One Way Association

### ISSUE THREAD

**Issue by shooom** [balderdashy/waterline#997] opened 2015-05-08 08:50 UTC
I'm using the Waterline ORM (PostgresQL adapter) with SailsJS and I have two models:

buildings:

```
{
  tableName: 'buildings',
  attributes: {
  id: {
    type: 'integer',
    primaryKey: true
  },
  BuildingName: {type: 'string'},
  BuildingBodyId:{model:'buildingbodies'}
}
```
bodybuildings:
```
{
  tableName: 'buildingbodies',
  id: {
    type: 'integer',
    primaryKey: true,
    required: true
  },
  RequiedBeInField: {type: 'integer'},
  BuildingViewState: {type: 'string'}
};
```
I trying to return all buildings and use next query:
```
buildings.find({
  select:['id','BuildingName','BuildingBodyId']})
  .populate('BuildingBodyId')
```
It's return to result:
```
 {
     "BuildingBodyId":{
       "id":2,
       "createdAt":"2015-05-07T12:46:55.501Z", 
       "updatedAt":"2015-05-07T12:46:55.501Z"},
     "id":1,
     "BuildingName":"YellowTeaField"
 }
```
i.e. BuildingBodyId return without RequiedBeInField and BuildingViewState. Can anyone give me a tip on how to get these two tables with all parameters? Thanks.

http://stackoverflow.com/questions/30106370/watelinejs-one-way-association

**Comment by dmarcelino** [comment] 2015-05-08 11:15
Does `BuildingBodyId` returns `RequiedBeInField` and `BuildingViewState` when you remove the `select` statement?

PS: it's general a good idea to type your full question here (in addition to the SO url). One of the advantages is that it will turn up in the results when searched for.

**Comment by shooom** [comment] 2015-05-08 11:30
dmarcelino, remove ```select``` doesn't help me.

**Comment by devinivy** [comment] 2015-05-08 12:24
Does this only occur when `RequiedBeInField` and `BuildingViewState` are empty on the record?  Are those columns definitely in your database?

**Comment by shooom** [comment] 2015-05-08 12:40
devinivy, yes, those columns are defined in database. and they are not empty.

**Comment by shooom** [comment] 2015-05-08 12:47
But next query:

```buildings.query(
      'SELECT * FROM buildings ' +
      'LEFT JOIN buildingbodies ' +
      'ON buildings.buildingbody_id = buildingbodies.id', function (err, results)```

return me all fields:

```{ id: 2,
    buildingname: 'my_building_name',
    createdAt: Fri May 08 2015 12:20:18 GMT,
    updatedAt: Fri May 08 2015 12:20:18 GMT,
    buildingbody_id: 2,
    requiedbeinfield: 1,
    buildingviewstate: 'Placed',
    buildingdata_id: 3,
    positionwithoutshape_id: 1 }```

**Comment by devinivy** [comment] 2015-05-08 13:10
You need to specify column names on your attributes if they don't match the attribute names exactly.  Could that be your issue?

**Comment by dmarcelino** [comment] 2015-05-08 13:23
> dmarcelino, remove select doesn't help me.

It would help us understand if there is a bug with `select` or if the issue is somewhere else.

**Comment by dmarcelino** [comment] 2015-05-13 17:13
Closing this as unresponsive, please re-open at any time with more information.

**Closed by dmarcelino** 2015-05-13 17:13 UTC
Labels: question
