### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by danieltjewett** [balderdashy/waterline#1319] opened 2016-03-02 16:19 UTC
I've seemed to run into a memory leak with waterline.  Below is a link to a repo at its simplest form:

https://github.com/rootinc/waterline-test

## Steps to reproduce bug:

1. Clone the Repo
2. Run `sails lift`
3. Put something in the DB by running this in the browser: `http://localhost:1337/test/create?name=Hello`
4. Reload this link over and over and watch the memory leak: `http://localhost:1337/testthis/1`

### OR

1. Make a vanilla sails app.
2. Then run `sails generate api Test`
3. In TestController, add route that looks like this: <pre>
testGet:function(req,res)
{
  var testId = req.param('testId');
  Test.findOneById(testId).then(function(test){
    res.send("Hi");
  });
}
</pre>
4. In Test.js (model), added property `schema:true`, and property called `name` that is required and a string.
5. In route.js, added this `'get /testthis/:testId' : 'TestController.testGet'`
6. In models.js, uncomment `migrate:'alter'`
7. Reboot the server running `sails lift`
8. Put something in the DB by running this in the browser: `http://localhost:1337/test/create?name=Hello`
9. Reload this link over and over and watch the memory leak: `http://localhost:1337/testthis/1`

I originally thought it was something with the Cheerio library due to a V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=2869 but after gutting everything related to Cheerio, memory was still leaking.  When returning before the DB call, memory was fine.  Once I put the code back in, the leak continued.

It is more noticeable with apps that return large amounts of data in fields.  For example, in my app, one of the fields returns a huge JSON string.  But, I would suspect that our other apps using waterline have this issue -- they just aren't returning as much data, therefore not as significant of an increase in memory.

 Any assistance on this would be great.  Thanks!

**Comment by particlebanana** [comment] 2016-03-02 17:00
@danieltjewett thanks for the repo. Could you do me a quick favor and try using the following to see if the behavior exists there?

```javascript
testGet: function(req,res) {
  var testId = req.param('testId');
  Test.findOne({ id: testId }).exec(function(err, test) {
    res.send("Hi");
  });
}
```

**Comment by danieltjewett** [comment] 2016-03-02 17:16
@particlebanana I tried the following and the behavior still exists.

**Comment by devinivy** [comment] 2016-03-02 19:09
What is your version of waterline?  And your version of sails?  I will spend some time on this if it can be reproduced with waterline standalone.

**Comment by danieltjewett** [comment] 2016-03-02 20:28
Waterline version is 0.10.26
Sails is 0.11.2

**Comment by mikermcneil** [comment] 2016-03-11 08:24
Hey @danieltjewett, it looks like you're using sails-disk (https://github.com/rootinc/waterline-test/blob/master/config/models.js) in the example repo you posted. If not, please let us know asap. 

sails-disk is not intended for production, and it stores the entire contents of your database in memory. This is awesome for a while, but eventually becomes impractical in production, like a California King bed in a tiny apartment. Again, if I'm missing something here and you're using a database, please correct me, and provide the adapter package and version you are using.

Thanks very much for providing such detailed repro instructions by the way.

**Comment by danieltjewett** [comment] 2016-03-11 14:51
@mikermcneil I am using sails-disk for this example -- thanks for the catch/clarification.  However, when I first noticed this issue, I was using someMongodbServer as my DB.  I will try to verify in the next couple hours that the example repo I provided, using someMongodbServer, causes a memory leak.

For the time being, I am invoking `global.gc` every 15 minutes to clean up some memory.  That seems help, but I know that is not a permanent solution.

**Comment by mikermcneil** [comment] 2016-03-11 18:07
@danieltjewett okay I'm going to go ahead and close this issue, since this is the expected behavior of sails-disk. if you find there is an issue when using Mongo or any other database, please create a new issue and link back here. Thanks again for the help!

**Closed by mikermcneil** 2016-03-11 18:07 UTC

**Comment by mikermcneil** [comment] 2016-03-11 20:38
By the way: I've considered adding warning log message for when sails-disk is being used in a production environment for a while.  Thought process is that it would hopefully help remind folks something along the lines: "hey you're using sails-disk - it's for development only, it's not going to be scalable, and it can't hold any meaningful amount of production data."  (a la the connect session memory store warning)    Unless anyone has objections, I can add that in the next version.

**Comment by particlebanana** [comment] 2016-03-15 16:51
@danieltjewett looks like @mikermcneil added a check for using sails-disk in production to the ORM hook. 

I'm looking into your other issue and this [issue](https://github.com/balderdashy/sails/issues/3638) on Sails which is probably related.

**Comment by mikermcneil** [comment] 2016-08-09 21:17
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here: https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
