### ISSUE TITLE
Please add more attribute type

### ISSUE THREAD

**Issue by zieglar** [balderdashy/waterline#987] opened 2015-05-04 06:51 UTC
e.g posgres 's float8, beacuse float4 can't store complete latitude and longtide number.

**Comment by dmarcelino** [comment] 2015-05-04 09:16
Hi @zieglar, your request is a duplicate of #819 (which has the proposed PR #981) so I'm closing it for now. Please re-open if you don't agree. Thanks.

**Closed by dmarcelino** 2015-05-04 09:16 UTC
