### ISSUE TITLE
finding by association doesn't work

### ISSUE THREAD

**Issue by mkeremguc** [balderdashy/waterline#469] opened 2014-06-10 17:55 UTC
User.js
```
attributes: {
 groups: {
  collection: 'userGroup',
 }
}
```

UserGroup.js
```
attributes: {
 name: {
  type: 'STRING',
 }
}
```

when i try something like:
```
User
.find()
.where({groups: [1,2]})
.exec(function(err, user) {
 if (err) {
  res.json({ error: err }, 500);
 } else {
  res.json(user);
 }
});
```
it gives error:
```

-error: {
 error: "E_UNKNOWN"
 status: 500
 summary: "Encountered an unexpected error"
-raw: {
 code: "ER_BAD_FIELD_ERROR"
 errno: 1054
 sqlState: "42S22"
 index: 0
}
}
```

however, i do really need to search via blueprints like posting this to find method of the user controller:
```
{
 "where": {
   "groups": [1,2]
 }
}
```
it also gives server error 500 without details.

according to sails issue 124 which was the post about associations, the examples about finding through collections was like that: https://github.com/balderdashy/sails/issues/124#issuecomment-21690561

sorry if this is a sails issue and i posted this to wrong place. 

using sails v0.10-rc7 and waterline-v0.10-rc13

bug or error on my side ?

thanks

**Comment by mkeremguc** [comment] 2015-01-09 23:09
it still doesn't work for me

**Comment by AnalogJ** [comment] 2015-04-19 00:00
This isn't working for me either in Sails v0.11.0 
Is this a verified bug? Or just an unimplemented feature?

**Comment by dmarcelino** [comment] 2015-04-19 16:21
@mkeremguc, @AnalogJ, which adapters are you using?

Regarding `.where({groups: [1,2]})`, are `1` and `2` primary keys?

**Comment by mkeremguc** [comment] 2015-04-20 00:47
@dmarcelino, mysql and mongo

and yes, primary keys

**Comment by AnalogJ** [comment] 2015-04-20 02:14
@dmarcelino I'm using postgres

**Comment by dmarcelino** [comment] 2015-04-24 17:08
I'm just thinking... I'm not sure this functionality is in the spec, at least I don't recall it when I implemented sails-orientdb and I don't remember seeing it in the docs. Can someone PR a test to waterline-adapter-tests? That would help towards figuring out which adapters are broken/don't implement this and then we could work on getting it fixed/spec'ed.

**Comment by mkeremguc** [comment] 2015-04-24 22:31
there are lotsa features that is not in the docs either. however, that feature may not be implemented as @dmarcelino said. i was just referencing https://github.com/balderdashy/sails/issues/124#issuecomment-21690561 at the time.

even though it not be implemented yet, i would still ask how you search/find/filter by association values ? custom in-memory functions would not be efficient for large data sets.

btw, it gives empty array via blueprint at the moment.

**Comment by devinivy** [comment] 2015-04-27 13:37
This often relies on using `native` (mongo adapter) or `query` (sql adapters) adapter methods, which allows you to make queries directly through the database wrapper.

**Comment by dmarcelino** [comment] 2015-05-04 10:55
I believe for something like this to work (without resorting to `.native()` or `.query()`) we'll need the `.populateKeys()` feature being discussed in https://github.com/balderdashy/waterline/issues/532#issuecomment-97515874 or wait for #266.

**Comment by dmarcelino** [comment] 2015-05-20 22:57
Closing this as duplicate of #266, please re-open if you believe this is a different feature.

**Closed by dmarcelino** 2015-05-20 22:57 UTC
Labels: needs failing test, needs review
