### ISSUE TITLE
FindOne returns function instead of doing callback

### ISSUE THREAD

**Issue by elennaro** [balderdashy/waterline#1043] opened 2015-06-05 09:41 UTC
Only on my production environment (waterline@0.10.23+ sails-mongo@0.11.2 + async@0.9.2) the strange thing happens:

the code:
````
async.waterfall([
			function findCustomer(cb) {
				sails.log.verbose("findCustomer", req.param('customer'));
				!/^\+995.*$/.test(req.param('customer').phone)
								&& (req.param('customer').phone = "+995" + req.param('customer').phone);
				Customer.findOne({ 'phone': req.param('customer').phone }).exec(cb);
			},
			function customerUpdate(customer, cb) {
				sails.log.verbose("customerUpdate", customer);
				if (!customer || customer === undefined) {
					sails.log.silly("Will create new customer", req.param('customer'));
					Customer.create(req.param('customer')).exec(cb);
				} else {
					sails.log.silly("Will update customer", req.param('customer'));
					Customer.update({ 'phone': req.param('customer').phone }, req.param('customer')).exec(cb);
				}
			}
//Some Other logic
], function asyncComplete(err, data) {
			if (err)
				sails.log.error("Error", err);
			return res.created(data);
		});
````
Fails with error:
````
findCustomer { name: 'sandros', phone: '555555555' }
customerUpdate function (err) {
                if (err) {
                    callback.apply(null, arguments);
                    callback = function () {};
                }
                else {
                    var args = Array.prototype.slice.call(arguments, 1);
                    var next = iterator.next();
                    if (next) {
                        args.push(wrapIterator(next));
                    }
                    else {
                        args.push(callback);
                    }
                    async.setImmediate(function () {
                        iterator.apply(null, args);
                    });
                }
            }
Will update customer { name: 'sandros', phone: '+995555555555' }
Error: No Callback supplied, you must define a callback.
````
I don't even understand why... :(

**Comment by devinivy** [comment] 2015-06-06 00:18
Notice that when you logged `customerUpdate ...`, what you thought was the `customer` ended up being the callback!  Most likely there was no custom found during,
```
Customer.findOne({ 'phone': req.param('customer').phone }).exec(cb);
```
which threw-off waterfall.  Would waterfall pass along a null or undefined value?

**Comment by elennaro** [comment] 2015-06-06 17:59
As I know about how the Async's waterfall works:
* When  Customer.findOne's `exec(cb)` executes callback with `error != null` it executes the last function named `asyncComplete` in my code, but it does not, hence `error == null`, 
* When `error == null`, it executes the next function `customerUpdate`, and passes all the arguments that are passed from `exec(cb)` **directly, as is** (I hope so however there is [an issue](https://github.com/caolan/async/pull/519), not quite same but sometnig close to ours), extept first one (the error) to this function.

But instead of getting the returned customer object or `undefined`, i see the piece of code.

So does `Customer.findOne` really call cb with `null, undefined` parameters? And if so? Why is this bug happening only on `production`. I mean why assync handles this undefined ok when I'm in `development` and does not on --prod?

Maybe it's not Assync's fault? Maybe `Customer.findOne passes this piece of code instead of customer to the callback?  And why is it happening only on --prod?

**Comment by devinivy** [comment] 2015-06-06 23:34
The issue is that `findOne` calls the results callback without any arguments if there isn't a result.  This issue probably occurs in prod because of data differences– there's no issue if `findOne` _does_ return a result.  Try replacing
```node
Customer.findOne({ 'phone': req.param('customer').phone }).exec(cb);
```
with
```node
Customer.findOne({ 'phone': req.param('customer').phone }).exec(function(err, customer) {
  cb(err, customer);
});
```
 to ensure `cb` always gets the same number of arguments.

Maybe we should make a change to waterline so that results callbacks always have the same arity!  @dmarcelino @tjwebb what do you think?

**Comment by elennaro** [comment] 2015-06-07 08:08
@devinivy thank you so much for explanation!
You saved my day!

I want to mention, that IMHO a lot of developers use Async, so I vote for the same arity for all the callbacks in waterline.

**Comment by dmarcelino** [comment] 2015-06-07 11:06
> Maybe we should make a change to waterline so that results callbacks always have the same arity!

I totally agree. That would make behaviour much more predicable for callbacks.

**Comment by devinivy** [comment] 2015-06-07 17:21
Sure thing!  I'm going to close this out and open a new issue.

**Closed by devinivy** 2015-06-07 17:21 UTC
Labels: question
