### ISSUE TITLE
multiple sort order error

### ISSUE THREAD

**Issue by zieglar** [balderdashy/waterline#407] opened 2014-05-04 03:43 UTC
when I use sort like `.sort('firstletter asc').sort('id asc')` the Query sql is `ORDER BY b.id asc, b.firstletter asc`, but I need `ORDER BY b.firstletter asc, b.id asc`, please fix it!

**Comment by dmarcelino** [comment] 2015-04-23 19:11
@zieglar, are you still experiencing this? Which adapter are you using? Thanks

**Comment by dmarcelino** [comment] 2015-04-28 23:35
Closing this as duplicate of #694 which has a few suggestions on how to fix this. Thanks!

**Closed by dmarcelino** 2015-04-28 23:35 UTC
Labels: needs review
