### ISSUE TITLE
Populate multiple levels down

### ISSUE THREAD

**Issue by npfitz** [balderdashy/waterline#256] opened 2014-02-02 19:26 UTC
I'm wondering if there are any plans to have the populate function populate multiple levels down. For example, if I have a Document, which has a collections of Comments, and those Comments each have a Creator attribute that points to a User model, Should I be able to do something like: 
````
Document.findOne(1)
.populate("comments")
.populate("creator")
.exec(function(err, doc){
/*do stuff*/
});
````

**Comment by jakubstrama** [comment] 2015-03-15 18:59
+1

**Comment by dmarcelino** [comment] 2015-03-23 11:44
Closing this as a duplicate of #308, please continue the discussion there.

**Closed by dmarcelino** 2015-03-23 11:44 UTC

**Comment by felipecm** [comment] 2015-03-23 14:25
+1

**Comment by pavel-anisimov** [comment] 2015-03-25 20:13
+1

**Comment by dmarcelino** [comment] 2015-03-25 20:15
Please continue the discussion in #308.
