### ISSUE TITLE
finding containing string in ors

### ISSUE THREAD

**Issue by calidion** [balderdashy/waterline#1019] opened 2015-05-21 15:49 UTC
Model.find({
      "or": [
        {"field1": {"contains": "query"}},
        {"field2": {"contains": "query"}},
        {"field3": {"contains": "query"}}
      ]
    });

**Comment by dmarcelino** [comment] 2015-05-21 17:25
Hi @calidion, what's your question / issue?

**Comment by calidion** [comment] 2015-05-22 06:17
@dmarcelino 
currently find criteria only support exact matched search,
which is 

```sql
a = b
```
but sometimes we need searches like
```sql
a like "%b%"
```
and can be arranged in side `or` array.


turn this
```javascript
Model.find({
"or": [
{"field1":  "query"},
{"field2": "query"},
{"field3": "query"}
]
});
````
to this
```javascript
Model.find({
"or": [
{"field1": {"contains": "query"}},
{"field2": {"contains": "query"}},
{"field3": {"contains": "query"}}
]
});
````

**Comment by dmarcelino** [comment] 2015-05-22 10:13
Have you tried using `or` with `contains` in waterline? It's supported so it should work. There are some tests for it in [waterline-adapter-tests](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/queryable/modifiers/or.modifier.test.js#L58-L75) and it has come in other issues like https://github.com/balderdashy/waterline/issues/978#issuecomment-96598798. Is this happening with a specific adapter or more than one?

**Comment by calidion** [comment] 2015-05-22 15:10
i have tried.
It was anticipated to be able to work, but turned out to be not.
so I rewrote it with raw sql queries.

**Comment by dmarcelino** [comment] 2015-05-22 15:11
Which adapter were you using? Did you try another adapter?

**Comment by calidion** [comment] 2015-05-22 15:13
@dmarcelino  mysql adapter.  haven't tried any another adapter.

**Comment by dmarcelino** [comment] 2015-05-25 11:03
@calidion, I've submitted PR balderdashy/waterline-adapter-tests#76 which adds a test for `OR` with multiple `contains` mimicking your scenario and the test passes in all adapters including mysql as you can see in: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/63937899#L1657

The test itself:
```js
      it('should work correctly when OR is used with multiple contains modifiers', function(done) {
        Queryable.User.find({
          type: 'or test',
          or: [
            { first_name: { contains: 'user0' } },
            { last_name:  { contains: 'user1' } },
            { title:      { contains: 'title2' } }
          ]
        })
        .sort('first_name')
        .exec(function(err, users) {
          if(err) return done(err);

          assert(Array.isArray(users));
          assert.strictEqual(users.length, 3);
          assert.equal(users[0].first_name, 'OR_user0');
          assert.equal(users[1].last_name, 'contains_user1');
          assert.equal(users[2].title, 'contains_title2');
          done();
        });
      });
    });
```

Are you using the latest versions of waterline and sails-mysql?

**Comment by calidion** [comment] 2015-05-25 15:25
@dmarcelino 
 "sails-mysql": "0.10.6"
waterline are not included in the package, but the sails version is the most recent one.

**Comment by dmarcelino** [comment] 2015-05-25 15:31
You should be able to check your waterline version by doing `npm ls waterline`. If it's not the latest (v0.10.22) you can update it by going into sails folder, `cd node_modules/sails` and doing `npm update waterline`.

If that's not the issue is it possible that the data you have in your DB is not what you expect it to be?

**Comment by calidion** [comment] 2015-05-26 08:08
@dmarcelino 
should be the lastest version.

        options.online = {'!' : true};
and this won't work properly too.

**Comment by calidion** [comment] 2015-05-26 08:09
I would like to know how to get the full sql when every sql executed or error occurred.

**Comment by dmarcelino** [comment] 2015-05-30 19:12
Set environment variable `LOG_QUERIES=true`.

**Comment by calidion** [comment] 2015-05-31 05:33
@dmarcelino
I don't think we need to set this every time.
I think in debug mode, this option will always be true.

**Comment by dmarcelino** [comment] 2015-05-31 10:35
Not sure what you mean @calidion, `LOG_QUERIES=true` is for logging the SQL queries that sails-mysql produces, in response to what you asked earlier.

**Comment by calidion** [comment] 2015-06-01 15:01
I mean no need to set this PARAMETER when debugging.
throw whole sql whenever queries failed.

**Comment by dmarcelino** [comment] 2015-06-04 18:33
@calidion, have you found the root cause of the issue? Are you able to create a test like the one in https://github.com/balderdashy/waterline/issues/1019#issuecomment-105207246 that reproduces this?

**Comment by dmarcelino** [comment] 2015-06-09 14:28
Closing this as we were unable to reproduce (PR balderdashy/waterline-adapter-tests#76), anyway if an issue exists it's probably in the MySQL adapter and that should be discussed in https://github.com/balderdashy/sails-mysql.

**Closed by dmarcelino** 2015-06-09 14:28 UTC
Labels: question
