### ISSUE TITLE
Model#toJSON returns an object with a toJSON method

### ISSUE THREAD

**Issue by weblogixx** [balderdashy/waterline#891] opened 2015-03-18 12:37 UTC
Hi,

I am encountering an recursion error when using sails with socket.io redis while updating models. This seems to be related to msgpack sizeof, which tries to call the toJSON method of my model entities. It also does not make a difference if I use a custom or the builtin toJSON method.

Software versions:
OS: Windows 7 (64 bit)
node.js -> v0.12.0
sails: 0.11
socket.io-redis: 0.1.4
sails-mysql: 0.10.11

This is the output I get when trying to update via socket.io:
```
backend\node_modules\sails-mysql\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
              ^
RangeError: Maximum call stack size exceeded
    at Date.valueOf (native)
    at baseClone (backend\node_modules\sails\node_modules\waterline\node_modules\lodash\dist\lodash.js:765:29)
    at Function.cloneDeep (backend\node_modules\sails\node_modules\waterline\node_modules\lodash\dist\lodash.js:1799:14)
    at backend\node_modules\sails\node_modules\waterline\lib\waterline\model\lib\defaultMethods\toObject.js:114:26
    at Array.forEach (native)
    at toObject.addProperties (backend\node_modules\sails\node_modules\waterline\lib\waterline\model\lib\defaultMethods\toObject.js:112:27)
    at new module.exports (backend\node_modules\sails\node_modules\waterline\lib\waterline\model\lib\defaultMethods\toObject.js:34:8)
    at prototypeFns.toObject (backend\node_modules\sails\node_modules\waterline\lib\waterline\model\index.js:30:14)
    at prototypeFns.toJSON (backend\node_modules\sails\node_modules\waterline\lib\waterline\model\index.js:112:20)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:27)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:14)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:14)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:14)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:14)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:14)
    at sizeof (backend\node_modules\socket.io-redis\node_modules\msgpack-js\msgpack.js:466:14)
```

I digged a bit deeper and found:

```
// Part of msgpack.js that causes the error
if('function' === typeof value.toJSON) {
    return sizeof(value.toJSON())
}
```

From there, I was investigating the original toJSON method. It says:
```
  prototypeFns.toJSON = function() {
    var obj = this.toObject();

    if (protectedAttributes.length) {
      _.each(protectedAttributes, function(key) {
        delete obj[key];
      });
    }

    // Remove toJSON from the result, to prevent infinite recursion with
    // msgpack or other recursive object transformation tools.
    //
    // Causes issues if set to null and will error in Sails if we delete it because blueprints call it.
    //
    // obj.toJSON = null;

    return obj;
  };
```

So this seems to be a known issue. The question is, how do I get this fixed (best without modifying core files)? I could uncomment the obj.toJSON = null; line, but as the comment states, it may break things. Without socket.io redis support, it works great.

Thank you for your answers,
Christian

**Comment by weblogixx** [comment] 2015-03-18 12:42
Update, seems to be related to #879, but I use it without relations...

**Comment by devinivy** [comment] 2015-03-19 02:58
Blueprints only uses it here (if at all??).
https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actions/update.js#L72

This does seem like an issue/bug that needs to be ironed-out.  It should be safe to assume that whatever `obj.toJSON()` returns does not have a `toJSON` method.

@weblogixx are you using blueprints in your sails project?  If not, I'd be very interested to see what issues arise by removing that method.

**Comment by weblogixx** [comment] 2015-03-19 06:25
Yes, I do use blueprints.

I have a custom toJSON method that adds a custom field, but even commenting it out does not change anything.

The problem seems to be model#toObject. If I override this with static values in the model, the error does not appear. If I uncomment both toObject and toJSON in my model, the error is triggered in the original toObject method of the models.

**Comment by weblogixx** [comment] 2015-03-20 12:24
So I have found the problem. The toJSON method is calling toObject, which exports an object that has a toJSON method. Therefore, a quick fix is:

```
        toJSON: function toJSON() {
            var obj = this.toObject();
            delete obj.password;
            obj.toJSON = null;
            return obj;
        }
```

This is seems not to be very friendly for developers and should at least be documented, even if the error is only encountered when using msgpack.

**Comment by devinivy** [comment] 2015-03-22 17:19
The community needs to figure out how we ought deal with this.  It seems clear to me that `toJSON` must always return an object that does not have a `toJSON` method.  @weblogixx do you mind if I rename this issue to deal with that root cause, or would you rather we close this and create a new issue?

**Comment by weblogixx** [comment] 2015-03-22 18:08
I think you should rename it. There is at least one other person that has a similiar problem and I already set a backlink to this issue.

Also I think you are right, there should be no toJSON method when using model#toJSON. The problem (at least in my case) was that I was using an example from the webpage and the internals of sails are new to me (I thought it would strip it out).

I also think many other people that develop locally and want to use redis for communication sharing will run in this issue. If it cannot be fixed, it should at least be stated in the docs.

**Comment by tjwebb** [comment] 2015-03-22 18:12
Can someone succinctly re-state the issue? The actual problem is becoming muddled for me. 

I'm using toJSON with great success, e.g.
https://github.com/tjwebb/sails-auth/blob/master/api/models/User.js#L29-L35. It would help me out if someone can show how my use case is different.

**Comment by weblogixx** [comment] 2015-03-22 18:15
@tjwebb The problem occurs when using stuff like socket.io-redis, which internally uses msgpack. If you are using toJSON the way you do it, then it will export the original model#toObject minus the password. This seems to be fine. However, in this object you also export the toJSON method, which leads to recursion errors (the Object will always infinitly call model#toJSON because this exports its own toJSON method).

**Comment by tjwebb** [comment] 2015-03-22 18:16
Ok I think it's confusing that this issue is being discussed as if it affects all adapters. What is special about msgpack that causes it to break?

**Comment by devinivy** [comment] 2015-03-22 18:19
This issue is that the object that Model#toJSON returns iself has a toJSON method.  This is unnecessary and causes issues with msgpack here, where their `sizeof` function recursively calls `toJSON`, causing an infinite loop: https://github.com/creationix/msgpack-js/blob/master/msgpack.js#L464-L466 .

**Comment by weblogixx** [comment] 2015-03-22 18:19
Hi tj,

it is stated in my first post. In messagePack you have this little code snippet so the library can recursively create its own json representation:

I digged a bit deeper and found:

```
// Part of msgpack.js that causes the error
if('function' === typeof value.toJSON) {
    return sizeof(value.toJSON())
}
```

When using the socket.io support with socket.io-redis, the library will try to use the msgpacked version of your object.

**Comment by tjwebb** [comment] 2015-03-22 20:03
If toObject returns an object with methods, and toJSON docs says we should call toObject, there's no way to solve this problem in general without altering the API. Which is ok, but the bugfix for this likely won't make it in a patch release.

**Comment by weblogixx** [comment] 2015-03-22 20:11
From my point of view this is completely understandable. However it should be clearly stated in the documentation that the "regular" approach is not working seamlessly currently when using third party libraries.

Would it be an option to include a hotfix in sails-hook-sockets? The toJSON method could at least be stripped out there before tje redis connect.

**Comment by devinivy** [comment] 2015-03-22 20:16
Seems like there are at least two options to fix the root of the issue, and it sounds like the suggestion in waterline docs is wrong.  I think we should be able to fix this in a patch release with a little bit of creativity.
Either,
1.  Alter `toObject` to not include functions.  I don't know if pieces of code in waterline depend on this, and I don't know if it's considered to be a part of the API.
2. Wrap `Model#toJSON` to ensure it does not include a `toJSON` method.  Or allow the model definition to call a "parent" toJSON method which behaves appropriately.
3. Similarly to number 2, In the docs insist on using a new model method, i.e. `Model#toPlainObject` which does not include any methods itself.

**Comment by weblogixx** [comment] 2015-03-22 20:21
I think the cleanest way that I see without breaking compatibility would be option number two. toJSON would then behave like it is expected to work: Just an object representation without the attributes.

Personally I think #3 should not be an option (except for a small fix) as it would add unneeded complexity when leRning the framework. However, other people that know the internals should be asked.

**Comment by anasyb** [comment] 2015-03-31 17:49
> So I have found the problem. The toJSON method is calling toObject, which exports an object that has a toJSON method. 

Indeed... why would `toObject` do that... very unexpected. 

@devinivy I vote for option 1, and devote 2 and 3. After calling `toObject` and then doing some decorations to the returned object, res.ok(obj) simply calls again `toObject` and apply some rules that undo some stuff that was done... after a complete day of tracing this out had to simply do `obj.toJSON = undefined`

One would expect that after a call had been made to `toObject`.. waterline is out of the way and we're free to do whatever we want on the returned object... so definitely waterline functions should be stripped out. Hope this doesn't break other code... if so maybe pass an argument to `toObject`.

**Comment by weblogixx** [comment] 2015-04-01 05:26
@anasyb I think that toObject should indeed have a toJSON method, as every object and primitive has one.You could, for example, never transfer a waterline model as inline JSON in a view because you just could not parse it to JSON.

toJSON should just export the current items representation without functions. In our models, we could call something like parent.toJSON to get the original json object and alter it the way we need to. One problem I see with this approach is that you could NOT call the original models functions from it.

Another possibility would be something like an model based afterJSON event that automatically strips the models methods from the object you are returning. I think that this would also violate the way toJSON is expected to work.

Any other opinions?

**Comment by anasyb** [comment] 2015-04-01 06:01
good thoughts @weblogixx... 
1. I am in total agreement that a `toObject()` and `toJSON()` should be included on the raw record sent to the callback.  
2. in my opinion once you convert that record to an object using toObject, **waterline is out of business**.. almost all other methods are stripped out by that call. I think waterline's toObject and toJSON should likewise be stripped out. You have to keep in mind that waterlines `toObject` is **assuming** that its operating on a record... not on the kind of object returned by `toObject()` itself. To illustrate this:

```javascript
  User.findOne('xx').populateAll().exec(function(err, r) {
    console.log(r.toObject());//does not strip out populated 1-N associations like r.post
    console.log(r.toObject().toObject());//1-N associations are stripped out!!
  })
```
Mind you also that calling `toJSON()` on an object returned by `toObject()` results in that double calls effect behind the scenes. So definitely waterline's `toObject()` MUST be stripped out.

3. Now whether to include other `toObject` and `toJSON` of some sorts... that could be a possibility. But in my opinion, JS native stringification is enough and is what one expects to have (again I am not talking about the raw record, am talking about the obj returned by `toObject`).

**Comment by anasyb** [comment] 2015-04-01 06:30
@devinivy I am totally new to waterline's codebase... but after a quick check it doesn't seem there are places where waterline is expecting a `toObject` on the obj returned by `toObject`? 
- In case am wrong... then you really need to check my comment above... in more than location `toObject` is clearly assuming its working on a full fledge raw record not on the results returned by itself.
- In case am correct.. then maybe just let `toObject()` swap itself with another `toObject` just before returning. (I don't know if you can make sense out of that sentence!)

**Comment by devinivy** [comment] 2015-04-01 11:38
@anasyb the created object inherits the prototype of the original model (so it has `toObject` itself), and I'm not completely sure if that's necessary either: https://github.com/balderdashy/waterline/blob/master/lib/waterline/model/lib/defaultMethods/toObject.js#L31

I agree that there's probably some cleaning-up to do there.

**Comment by anasyb** [comment] 2015-04-01 16:18
exactly! It is inheriting the proto, and what am saying is that this should not be the case for two reasons:
- the object returned by `toObject` is no longer an instance of the model... its something else with different structure
- the functions in the proto that's being inherited are not designed to be called on such an object, they are designed to be called on a proper instance of the model. The example above `r.toObject().toObject()` illustrates exactly this

See the confusion this led in https://github.com/balderdashy/waterline/issues/317#issuecomment-88403284 just as we were discussing this issue over here!

**Comment by dmarcelino** [comment] 2015-04-27 20:27
@weblogixx, @anasyb, #969 has been merged to master, can you check if it fixes your issues?

**Comment by devinivy** [comment] 2015-05-15 01:13
Closing since this is allegedly fixed in master and the topic has become quiet!  Anyone feel free to reopen if deemed necessary.

**Closed by devinivy** 2015-05-15 01:13 UTC
Labels: bug

**Comment by pfzero** [comment] 2015-08-04 15:43
Do you guys know what is the problem here? I think it's related to this issue.

I think that the methods are not deleted, in some circumstances. Please note that I am calling `toObject` on a model instance that it ```isn't populated at all```. It's just retrieved from the database and called toJSON on the model. it seems that the methods are ``not removed at all``.

```javascript
/**
 * Filter Functions
 *
 * @api private
 */

toObject.prototype.filterFunctions = function() {
  for(var key in this.object) {
    if(typeof this.object[key] === 'function') {
      this.object[key] = undefined;
      delete this.object[key];
      if (this.object.id === "c9d960d5-15b1-448c-b7ec-52b3b35032d7") {
        if(key === "toJSON") {
          console.log(Object.getOwnPropertyDescriptor(this.object[key])); //output: undefined
          console.log(key, this.object[key]); //output: toJSON function() ...
        }
        // this.object[key] = undefined;
      }
    }
  }
```

If I decomment the line with `this.object[key] = undefined`, it will work. I mean, the keys will still be there but undefined.

Any insights on this?

**Comment by pfzero** [comment] 2015-08-04 16:03
Ok, so I checked once again and I modified the code to get more insights (still using console.log).
Code...
```javascript
/**
 * Filter Functions
 *
 * @api private
 */

toObject.prototype.filterFunctions = function () {
  if (this.object.id === "c9d960d5-15b1-448c-b7ec-52b3b35032d7") {
    console.log(Object.getOwnPropertyNames(this.object));
    console.log(this.object.inspect);
  }
  for (var key in this.object) {
    if (typeof this.object[key] === 'function') {
      if (this.object.id === "c9d960d5-15b1-448c-b7ec-52b3b35032d7") {
        if (key === "toJSON") {
          console.log(Object.getOwnPropertyDescriptor(this.object[key]));
          console.log(Object.hasOwnProperty(this.object, key));
        }
      }
      delete this.object[key];
      if (this.object.id === "c9d960d5-15b1-448c-b7ec-52b3b35032d7") {
        if (key === "toJSON") {
          console.log(key, this.object[key]);
          console.log(Object.hasOwnProperty(this.object, key));
        }
      }
    }
  }
};
```

And text output...
```
[ 'createdAt', 'inspect', 'owner', 'id', 'ownerType', 'updatedAt' ]
[Function]
undefined
false
toJSON function () {
    var obj = this.toObject();

    if (protectedAttributes.length) {
      _.each(protectedAttributes, function(key) {
        delete obj[key];
      });
    }

    // Remove toJSON from the result, to prevent infinite recursion with
    // msgpack or other recursive object transformation tools.
    //
    // Causes issues if set to null and will error in Sails if we delete it because blueprints call it.
    //
    // obj.toJSON = null;

    return obj;
  }
false
```

Second output (this time caused by res.json or JSON.stringify, which are the same)...
```
[ 'createdAt', 'owner', 'id', 'ownerType', 'updatedAt' ]
undefined
undefined
false
toJSON function () {
    var obj = this.toObject();

    if (protectedAttributes.length) {
      _.each(protectedAttributes, function(key) {
        delete obj[key];
      });
    }

    // Remove toJSON from the result, to prevent infinite recursion with
    // msgpack or other recursive object transformation tools.
    //
    // Causes issues if set to null and will error in Sails if we delete it because blueprints call it.
    //
    // obj.toJSON = null;

    return obj;
  }
false
```

You can see that the inspect method is removed successfully, whereas toJSON method is not removed. After calling the toJSON method, I am populating it with other attributes, which are removed when sent to browser (this is an older issue, #317, which had as solution to convert the model instances to plain objects and "operate" on them).

This, unfortunately doesn't happen all the time, as for other models, this works without problems. The only difference between this model and the others (the good models), is that this model has some "one to many" defined properties.


Sorry for the long comment.
