### ISSUE TITLE
Cannot use attribute `type: 'longtext'` because it always fails validation

### ISSUE THREAD

**Issue by cspotcode** [balderdashy/waterline#878] opened 2015-03-05 22:05 UTC
Anchor doesn't have a validation rule for 'longtext', so if any of your model attributes have `type: 'longtext'`, they will always fail validation.

**Comment by dmarcelino** [comment] 2015-03-23 18:26
Closing this as duplicate of balderdashy/anchor#71 (which should be fixed by balderdashy/anchor#73). Please reopen if the referred issue and PR don't fix this.

**Closed by dmarcelino** 2015-03-23 18:26 UTC
