### ISSUE TITLE
Querying on many-to-many relationship

### ISSUE THREAD

**Issue by cava23** [balderdashy/waterline#1011] opened 2015-05-18 04:05 UTC
I'm moving over to Waterline/postgres from mongoose and I'm having an issue querying when there is a many-to-many relationship. In the pets example, if a pet can have many owners and an owner can have many pets, can I easily query for pets with a particular owner?

I save the pets like this:
```
petsCollection.create({name:"fido", owner: 2})
```

Now I want to find all the pets with owner "2". If I do:
```
petsCollection.find({owner:2})
```
I get an error that says owner is not a column. What am I doing wrong?

Thanks in advance.

**Comment by dmarcelino** [comment] 2015-05-18 11:20
Hi @cava23, I'm afraid that's not possible yet, #469 has been raised for implementing that functionality.

There are some workarounds you can use. For example you can find owner '2' and populate all his pets, something like:
``` javascript
ownersCollection.find({owner:2}).populate('pets')
```
More about `.populate` [here](https://github.com/balderdashy/waterline-docs/blob/be0d2b7d0c4fbee9a6dcbe1fc7fe74981708e0ef/query.md#populate).

Since you are using sails-postgresql you can also use the `.query()` method which allows you to run a *raw* SQL query. Details [here](https://github.com/balderdashy/waterline-docs/blob/67545664138e7362640756dd97205142cc72cac9/query-methods.md#query-query-data-callback-).

**Comment by dmarcelino** [comment] 2015-05-20 22:52
Closing this as a duplicate of #469. Please re-open if you disagree or this hasn't been fully answered.

**Closed by dmarcelino** 2015-05-20 22:52 UTC
Labels: question
