### ISSUE TITLE
findOrCreate method fails when json attribute on model is empty with postgresql

### ISSUE THREAD

**Issue by orthodoc** [balderdashy/waterline#979] opened 2015-04-27 07:26 UTC
Referring to balderdashy/sails-postgresql/issues/155
Model: User.js
Attribute: `socialProfiles: { type: 'json', defaultsTo: {} }`

Failing with an error `error: column user.socialProfiles.facebook.id does not exist`, when it should be creating a record.

**Comment by dmarcelino** [comment] 2015-04-27 09:02
@orthodoc, is this issue affecting other adapters besides sails-postgresql?

Can you share a code snippet on how you are using findOrCreate?

Are there any beforeCreate or beforeValidate  lifecycle callbacks that can be throwing this error?

**Comment by dmarcelino** [comment] 2015-04-27 19:00
Closing this as a duplicate of balderdashy/sails-postgresql#155 which seem to have already gathered some good quality answers. If there is an issue specific to waterline core feel free to reopen.

**Closed by dmarcelino** 2015-04-27 19:00 UTC
