### ISSUE TITLE
JSON.stringify() a model skips some properties

### ISSUE THREAD

**Issue by pixelfreak** [balderdashy/waterline#317] opened 2014-03-13 07:43 UTC
I'm on Sails 0.10. When I do JSON.stringify(someModel), some properties, specifically properties associated with other model is not outputted. How do I get it enumerated?

Thanks!

**Comment by andrewjmead** [comment] 2015-01-30 00:37
+1 this is still an issue for me. I'm using `0.10.16`.

**Comment by wallaceicy06** [comment] 2015-02-09 23:09
+1 this is still an issue for me as well

**Comment by anasyb** [comment] 2015-03-04 19:27
This is still an issue. A simple (but very bad) workaround is to set the .toJSON property of the returned record to anything other than a function, for example:
```javascript
User.find().exec(function(err, users){
  console.log(JSON.stringify(users[0]))
})
//{ id:1, name:'Susan'} //no post IDs!

User.find().exec(function(err, users){
  console.log(users[0].posts);
})
//['1', '2', '3', add:[Function add], remove:[Function remove]]  //but actually here they are!!

User.find().exec(function(err, users){
  users[0].toJSON="I won't allow you to use sails toJSON, just use the native stringification";
  console.log(JSON.stringify(users[0]))
})
//{ id:1, name:'Susan', posts:[1,2,3]} //post IDs are back!

```
As indicated by @particlebanana this is a problem with toObject, in particular it has to do with this [line, blame it for all this mess!](https://github.com/balderdashy/waterline/blob/master/lib/waterline/model/lib/defaultMethods/toObject.js#L145). Fixing the if condition or commenting it in your local waterline solves the problem, which is obviously a much better workaround, that is until it get official fixed.

This is very related to the *user-case* behind https://github.com/balderdashy/waterline/issues/532, although it is a completely separate issue. cc @mphasize

**Comment by tjwebb** [comment] 2015-03-04 19:45
@particlebanana this was marked In Progress forever ago. is there any update or did it call through the cracks

**Comment by devinivy** [comment] 2015-03-26 02:07
Any word here? @anasyb do you think your fix is solid enough to submit a PR?

**Comment by anasyb** [comment] 2015-03-26 02:53
@devinivy I had it running for a while with that line commented out... no notice of anything going wrong. Before a PR I suppose we need an understanding of what that's line purpose in life is/was.

Can someone run the tests with that line commented and post here which ones fail (if any)?

**Comment by devinivy** [comment] 2015-03-26 03:30
I wonder if `showJoins` is possibly not being accounted for on that line.

If someone could even write a failing test [here](https://github.com/balderdashy/waterline/blob/4653f8a18016d2bcde9a70c90dd63a7c69381935/test/unit/model/toObject.js), that would be awesome.

**Comment by anasyb** [comment] 2015-03-27 17:42
Test case should be fairly simple, test if an association that has some items in it (therefore .length > 0) has same .length before and after calling .toObject(). Here is an example:

```javascript
User.find().exec(function(err, rec){
  //15 (or whatever length truly is!)
  console.log(rec[0].posts.length);

  //0 (even though length isn't 0 as shown above)
  console.log(rec[0].toObject().posts.length);

  //false (so this should be the test case)
  console.log(rec[0].posts.length===rec[0].toObject().posts.length 
    && rec[0].posts.length !== 0);
})
```

Sorry didn't have time as yet to put that into a test file... let me know if you can do that :P

**Comment by anasyb** [comment] 2015-03-28 17:48
@devinivy interesting.. seems like there is a [test case](https://github.com/balderdashy/waterline/blob/master/test/unit/model/toObject.js#L53) to make sure the bug is there :D maybe we're missing something?!

If we're not missing something: assuming ```new model({ name: 'foobar' });``` is creating the association arrays (otherwise the existing test cases doesn't make sense to me?!) I would change that case to:

```javascript
      it('should NOT strip out the association key when no options are passed', function() {
        var person = new model({ name: 'foobar' });
        var obj = person.toObject();

        assert(obj === Object(obj));
        assert(obj.name === 'foobar');
        assert(obj.bars);
        assert(obj.foobars);
        assert(person.bars);
        assert(person.foobars);

        assert(person.bars.length === obj.bars.length);
        assert(person.foobars.length === person.foobars.length);
      });
```

**Comment by dmarcelino** [comment] 2015-03-28 18:04
One possible reason for removing the associations (I'm speculating) is to avoid circular references before using `.toJSON()`. If by any chance that is the reason we need to *decycle* the object. It would be good to hear from the guys who actually wrote that code about this.

**Comment by anasyb** [comment] 2015-03-28 18:15
Interesting... though on a second thought I can't see how cycles can emerge given that the [if statement](https://github.com/balderdashy/waterline/blob/master/lib/waterline/model/lib/defaultMethods/toObject.js#L145) is doing the opposite: it's returning when the join wasn't used (which means the IDs will stay mere strings)

**Comment by m0g** [comment] 2015-03-31 14:12
Hi, I'm using Waterline v0.10.19 and I'm having the same issue.

```
Question.findOne({ id: req.params.id })
      .populate('responses')
      .populate('options')
      .exec(function(err, question) {
        res.json(question.toObject());
      });
```

And in the browser ```responses``` & ```options``` are now gone.

```
"survey": 120,
"title": "...",
"number": null,
"maxNumericDigits": null,
"responseType": null,
"isConditional": null,
"numChoice": null,
"synced": null,
"type": "binary",
"id": 455,
"createdAt": "2015-03-31T11:08:41.000Z",
"updatedAt": "2015-03-31T11:08:41.000Z"
```

**Comment by anasyb** [comment] 2015-03-31 16:38
Hi @m0g !
Sorry the workarounds I posted above might not work as they did for me... it turned out I was so lucky that a [bug](https://github.com/balderdashy/sails-mongo/issues/254) was allowing it to work for me!
The strange thing in your code is that you're already populating... so stripping out the associated record should be de-activated on your toObject by default!

Here is a quick and dirty code snippet that keeps only the IDs if that's what you're after, can you try that?

```javascript
var Model = Question;

//populates those of N cardinality on any/both side(s)
var populateManyAssociations = function ( query, associations) {
  var query = query;
  for (var i = associations.length - 1; i >= 0; i--) {
    var assoc = associations[i];
    //if cardinality isn't many skip
    if (assoc.type !== "collection") continue;
    query = query.populate(assoc.alias);
  };
  return query;
}

var query = Model.findOne({ id: req.params.id });
query = populateManyAssociations(query, Model.associations);
query.exec(function(err, r) {
  var robj = r.toObject();
  function getId (obj){
    if (obj)  return obj.id;
  }

  //now manually keep IDs
  for (var i = Model.associations.length - 1; i >= 0; i--) {
    var assoc = Model.associations[i];

    //if cardinality isn't many skip
    if (assoc.type !== "collection") continue;

    robj[assoc.alias] = robj[assoc.alias].map(getId);
  };

  res.json(robj);
});
```

**Comment by m0g** [comment] 2015-04-01 09:04
Hey @anasyb, thanks for you help.

Let me elaborate a bit more.

What I want to do is to convert ```question``` into an object. Because I want to be able to override the content of ```question.options``` if ever I feel like doing so.

If I don't convert ```question``` to object then I can't override the options, unless I add a custom property like ```question.customOptions = customOptions```.

And if I do convert ```question``` to an object then all the associations are disappearing when outputting to JSON (but remains on the console.log).

Here is an example:

```
var populateManyAssociations = function ( query, associations) {
  for (var i = associations.length - 1; i >= 0; i--) {
    var assoc = associations[i];
    //if cardinality isn't many skip
    if (assoc.type !== "collection") continue;
    query = query.populate(assoc.alias);
  }

  return query;
};

 var query = Question.findOne({ id: req.params.id });
    query = populateManyAssociations(query, Question.associations);

    query.exec(function(err, question) {
      var questionObj = question.toObject();

      var getId = function(obj) {
        return obj;
      };

      for (var i = Question.associations.length - 1; i >= 0; i--) {
        var assoc = Question.associations[i];

        if (assoc.type !== "collection") continue;

        questionObj[assoc.alias] = questionObj[assoc.alias].map(getId);
      }

      console.log('responses', questionObj.responses.length);
      res.json(questionObj);
  });

```

**Server side output**

```
responses 1196
```

**Browser output**

```
{"survey": 120,
"title": "...",
"number": null,
"maxNumericDigits": null,
"responseType": null,
"isConditional": null,
"numChoice": null,
"synced": null,
"type": "binary",
"id": 455,
"createdAt": "2015-03-31T11:08:41.000Z",
"updatedAt": "2015-03-31T11:08:41.000Z"}
```

Thanks

**Comment by dmarcelino** [comment] 2015-04-01 09:16
I'm wondering if this can be caused by #891 (Model#toJSON returns an object with a toJSON method)?

**Comment by m0g** [comment] 2015-04-01 10:49
So I figured out an ugly workaround to my issue. If you guys are interested.

Here it is

```
somethingReturningCustomOptions(function(err, customOptions) {
  Question.findOne({ id: req.params.id })
    .populate('responses')
    .populate('options')
    .exec(function(err, question) {
      var assocs = []
        , questionObj = {};

      for (var i = Question.associations.length - 1; i >= 0; i--) {
        var assoc = Question.associations[i];
        if (assoc.type !== "collection") continue;
        assocs.push(assoc.alias);
      }

      var questionKeys = Object.keys(question).filter(function(key) {
        return (assocs.indexOf(key) == -1);
      });

      // We create a new object that has all 
      // the properties minus the associations
      questionKeys.forEach(function(key) {
        questionObj[key] = question[key];
      });

      // Then we can manually add the associations
      questionObj.responses = question.responses;

      // If we have some customOptions then we override
      // the question.options property
      questionObj.options = (customOptions) ? customOptions : question.options;

      res.json(questionObj);
    });
});
```

**Comment by anasyb** [comment] 2015-04-01 16:11
@m0g sorry you had to go as far as that... this is indeed caused by #891... in particular please read this comment https://github.com/balderdashy/waterline/issues/891#issuecomment-88361748

All you need is to stop waterline from being involved in your object. You can do so simply by:

```javasript
var questionObj = question.toObject();
questionObj.toJSON = undefined;//this will stop waterline's `toJSON` from being called

//...now do whatever you want with your obj
//...
res.json(questionObj);
```

**Comment by dmarcelino** [comment] 2015-04-27 20:28
@m0g, @dantswain, @pixelfreak, #969 has been merged to master, can you check if it fixes your issues?

**Comment by dmarcelino** [comment] 2015-05-15 14:24
As @devinivy said back in #891:
> Closing since this is allegedly fixed in master and the topic has become quiet! Anyone feel free to reopen if deemed necessary.

**Closed by dmarcelino** 2015-05-15 14:24 UTC
Labels: bug, needs failing test
