### ISSUE TITLE
Cannot pipe model data to socket.io socket

### ISSUE THREAD

**Issue by mlagace** [balderdashy/waterline#993] opened 2015-05-05 13:53 UTC
I'm trying to pipe data to a socket.io client using this example: http://sailsjs.org/#!/documentation/reference/waterline/models/stream.html

When I try the example I keep getting this error:

    TypeError: undefined is not a function at Stream.pipe (stream.js:65:8)

and the last line of the error shows:

    node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:425:11 [TypeError: undefined is not a function]

This is my code in my UserController:

    if (req.isSocket) {
      var getSocket = req.socket;
      User.stream({name: {'contains': req.query.q}}).pipe(getSocket.emit);
    }

When I check the stream data, I see all the user records like I should. I'm using in my Sails app:
* sails 0.11.0
* sails-mongo 0.10.5
* socket.io-redis 0.1.4

Anyone ever encountered this error before?

**Comment by dmarcelino** [comment] 2015-05-15 14:27
Hi @mlagace! Have you found a solution for your issue or the root cause for it? If not, perhaps you'll have better luck getting an answer in the [sails-mongo](https://github.com/balderdashy/sails-mongo) project or even [stackoverflow (tag 'waterline')](http://stackoverflow.com/questions/tagged/waterline).

**Comment by mlagace** [comment] 2015-05-15 14:33
Hi @dmarcelino! I wasn't able to find the root cause of the issue. The only way I could stream my data is by doing:

    var stream = User.stream(query);
    stream.on('data', function(chunk){
        sails.sockets.emit(req.socket.id, chunk.toString());
    });

which I'm not sure it's a good thing but for now it works really well.

**Comment by dmarcelino** [comment] 2015-05-15 14:36
I see, good to know you found a solution! Maybe it's worth raising an issue in the sails project questioning if their docs are accurate since you had to use a different solution.

I'm closing this for now but feel free to re-open it if you think it's worth further pursuing it.

**Closed by dmarcelino** 2015-05-15 14:36 UTC

**Comment by mlagace** [comment] 2015-05-15 14:38
Ok thanks @dmarcelino when I get more time I'll investigate further.
