### ISSUE TITLE
update(): set a `collection` attr w/ an array of primary keys

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/waterline#290] opened 2014-03-02 19:28 UTC
See https://github.com/balderdashy/sails/issues/1427#issuecomment-36403028
and roadmap item (Trello): https://trello.com/c/cWE9GE1D

**Comment by dmarcelino** [comment] 2015-04-24 16:43
@mphasize, take a look at #965, I think it may actually be a duplicate of this one. I've also modified the waterline-adapter-tests and they should pick this: PR balderdashy/waterline-adapter-tests#51. What do you think?

**Comment by mphasize** [comment] 2015-05-02 20:03
@dmarcelino I think my original issue is already addressed, since waterline/#506 is closed. But your work seems to have uncovered another issue, so I guess even though it might not be a duplicate, this issue could probably be closed.

**Comment by dmarcelino** [comment] 2015-05-02 22:48
Thanks @mphasize.

**Closed by dmarcelino** 2015-05-02 22:48 UTC
Labels: feature
